services:
  owrt-musicbox:
    build:
      context: .
      network: host
    container_name: owrt-musicbox
    restart: unless-stopped
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /dev/snd:/dev/snd
      - /var/run/dbus:/var/run/dbus
      - /mnt:/mnt:ro
      - ./data:/app/data
    environment:
      - OWRTMB_PORT=${OWRTMB_PORT:-2030}
      - OWRTMB_HOST=${OWRTMB_HOST:-0.0.0.0}
      - OWRTMB_DB_PATH=/app/data/music.db
      - OWRTMB_LOG_LEVEL=${OWRTMB_LOG_LEVEL:-INFO}
      - OWRTMB_DEFAULT_PATH=${OWRTMB_DEFAULT_PATH:-/root/music}
    devices:
      - /dev/snd
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
    stdin_open: true
    tty: true